version: '3'
services:
  developer-portal-fe:
    build: .
    image: developer-fe
    container_name: developer-fe
    command: yarn start
    ports:
      - 3030:3030

  common: &BASE
    build: .
    environment:
        - KEY

  ci-production:
    <<: *BASE
    command: yarn build:production

  test:
    <<: *BASE
    command: yarn test

  build:
    <<: *BASE
    command: yarn build
